#!/usr/bin/env bash

# http://stackoverflow.com/a/4774063
pushd `dirname $0` > /dev/null
ROOT_DIR=$(dirname `pwd -P`)
popd > /dev/null

SALT_DIR=$ROOT_DIR/k8s-salt
TERRAFORM_DIR=$ROOT_DIR/k8s-terraform
VELUM_DIR=$ROOT_DIR/velum

log()   { echo ">>> $1" ; }

# Usage: fetch_repo "my_repo_url", commit_or_branch, "dir_name"
fetch_repo() {
  log 'Fetching '$1

  new_dir="$ROOT_DIR/$3"
  mkdir -p $3
  cd $3
  git init
  git remote add origin $1
  git fetch origin
  git reset --hard origin/$2
  cd $ROOT_DIR
}
