#!/usr/bin/env bash

log()   { echo ">>> $1" ; }

SALT_DIR=$PWD/k8s-salt
TERRAFORM_DIR=$PWD/k8s-terraform
VELUM_DIR=$PWD/velum

# Usage: fetch_repo "my_repo_url", "dir_name"
fetch_repo() {
  log 'Fetching '$1

  new_dir="$PWD/$3"
  old_dir=$PWD
  mkdir $3
  cd $3
  git init
  git remote add origin $1
  git fetch origin
  git reset --hard origin/$2
  cd $old_dir
}

fetch_repo 'https://gitlab.suse.de/docker/k8s-salt.git' master $SALT_DIR
fetch_repo 'https://gitlab.suse.de/docker/k8s-terraform.git' master $TERRAFORM_DIR
#fetch_repo 'https://github.com/kubic-project/velum.git' master $VELUM_DIR
# TODO: change this when we merge velum non interactive mode
fetch_repo 'https://github.com/jimmykarily/pharos.git' use_flags_to_automate_development_env $VELUM_DIR

# Spawn the velum "development" environment (dashboard, salt-master,
# salt-api, ca, etcd)
cd $VELUM_DIR/kubernetes
SALT_DIR=$SALT_DIR ./start --non-interactive & # Daemonize this and loop until its ready

# Wait until the dashboard is up and running
until $(curl -s http://127.0.0.1:3000/ | grep -q "Log in")
do
  log "Waiting for testing environment to be ready"
  sleep 5
done

exit 0;
