#!/usr/bin/env bash

# Kill the kubelet which is started with a config file inside the working directory
# TODO: Remove sudo when we stop using sudo to lauch the kubelet
sudo kill $(ps aux | grep kubelet | grep $PWD | awk '{print $2}')
